# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Corona"
  pre = "<i class='fa fa-chart-line'></i>"
  url = "https://datastudio.google.com/s/vaXNAo7xk84"
  weight = 5

[[main]]
  name = "Home"
  pre = "<i class='fa fa-home'></i>"
  url = "#"
  weight = 10

[[main]]
  name = "Experience"
  pre = "<i class='fa fa-laptop-code'></i>"
  url = "#experience"
  weight = 20

[[main]]
  name = "Projects"
  pre = "<i class='fa fa-tasks'></i>"
  url = "#projects"
  weight = 30

[[main]]
  name = "Contact me"
  pre = "<i class='fa fa-address-card'></i>"
  url = "#contact"
  weight = 40

[[main]]
  name = "CV"
  pre = "<i class='fa fa-file-pdf'></i>"
  url = "https://github.com/suphero/cv/raw/master/English/Harun%20Sokullu.pdf"
  weight = 50

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
